[Testing Algorithms Project]
kspshnik/algo-school pull request #4
Opened 2023-04-26 23:16 UTC by kspshnik

Unit tests with Jest & react-testing-libraty. E2E with Cypress

2023-04-27 04:55 UTC, andryxxa93 requested changes
Супер! `Jest` тесты и `Cypress` настроены и работают верно. 
Что понравилось:
- Все Jest тесты (35 шт) проходят успшено. 
- Для одной функции `it` используется один `expect` - это хорошая практика.
- Тщательное E2E тестирование.
- Использовали константы селекторы.

**Необходимо исправить**
- При запуске проекта выдает ошибки eslint - это мешает тестированию

<img width="1434" alt="Снимок экрана 2023-04-27 в 07 47 14" src="https://user-images.githubusercontent.com/60173362/234762519-aee212ce-843f-4781-9cb0-f80cd08ec33a.png">

- Один тест падает 

<img width="704" alt="Снимок экрана 2023-04-27 в 07 53 43" src="https://user-images.githubusercontent.com/60173362/234762769-de711f31-f1e0-4e1a-ad28-505685d9969f.png">

Удачных правок!

2023-04-27 06:32 UTC, kspshnik commented
> **Необходимо исправить**
> 
> * При запуске проекта выдает ошибки eslint - это мешает тестированию
> 

Обе ошибки - в **предоставленном** Практикуме компоненте. Это не мой код, это то, что пришло из шаблона репозитория. 

> * Один тест падает
Исправлено.

2023-04-27 06:47 UTC, kspshnik commented
> * При запуске проекта выдает ошибки eslint - это мешает тестированию

У меня не воспроизводится :(
https://disk.yandex.ru/i/T8ZQRtJmBrL83Q
https://disk.yandex.ru/i/T8ZQRtJmBrL83Q
https://disk.yandex.ru/i/T8ZQRtJmBrL83Q

То есть в IDE подсвечивается, но на запуск не влияет.
И победить их можно только отключив соответствующие правила, ещё раз повторюсь - это предложенный Практикумом код в составе UI проекта.

2023-04-27 14:10 UTC, kspshnik commented
> * При запуске проекта выдает ошибки eslint - это мешает тестированию 

Исправлено, правила отключены т.к. в данном случае не влияют на мой код и не вызовут ошибок, мотивировавших к их включению. Источником правил послужили дополнительные плагины ESLint, выдвигающие более строгие требования к коду, чем требуется по умолчанию. Правила отключены для конкретных строк, где это безопасно для кода, но мешает при тесте.

2023-04-28 04:58 UTC, andryxxa93 commented
Супер, вы отлично поработали!
Поздравляю! Работа принята.
Желаю удачного продолжения обучения!

2023-04-28 09:05 UTC, merged